version: '4.9'

services:
  main:
    container_name: main
    build:
      context: .
    env_file:
      - .env
    ports:
      - "2000:2000"
    command: npm run start:dev
    depends_on:
      - postgres
    restart: always
  postgres:
    container_name: postgres
    image: postgres:14
    env_file:
      - .env
    environment:
      PG_DATA: /var/lib/postgresql/data/pgdata
      POSTGRES_HOST_AUTH_METHOD: "trust"
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
    restart: always

volumes:
  pgdata:    