version: '4.9'

services:
  main:
    container_name: main
    build:
      context: .
    env_file:
      - .env
    ports:
      - "2000:2000"
    command: npm run start:dev
    depends_on:
      - postgres
    restart: always
  postgres:
    container_name: postgres
    image: postgres:16.1
    env_file:
      - .env
    environment:
      PG_DATA: /var/lib/postgresql/data
      POSTGRES_PASSWORD: 1234
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always

volumes:
  pg_data:    